/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hangmangame;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author sisin
 */
public class TheGame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    public TheGame() {
        initComponents();
        setSize(1000,1000);
        setLocation(50,30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hatter = new javax.swing.JLabel();
        fember = new javax.swing.JLabel();
        aember = new javax.swing.JLabel();
        alja = new javax.swing.JLabel();
        kozepe = new javax.swing.JLabel();
        teteje = new javax.swing.JLabel();
        bember = new javax.swing.JLabel();
        gomba1 = new javax.swing.JLabel();
        kerdes1 = new javax.swing.JLabel();
        valasz1 = new javax.swing.JTextField();
        kerdes2 = new javax.swing.JLabel();
        valasz2 = new javax.swing.JTextField();
        kerdes3 = new javax.swing.JLabel();
        valasz3 = new javax.swing.JTextField();
        kerdes4 = new javax.swing.JLabel();
        valasz4 = new javax.swing.JTextField();
        jLab_W = new javax.swing.JLabel();

        hatter.setBackground(new java.awt.Color(89, 64, 64));
        hatter.setForeground(new java.awt.Color(97, 75, 75));
        hatter.setText("jLabel1");
        hatter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        hatter.setMaximumSize(new java.awt.Dimension(1000, 1000));
        hatter.setMinimumSize(new java.awt.Dimension(1000, 1000));
        hatter.setPreferredSize(new java.awt.Dimension(1000, 1000));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(119, 83, 83));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        fember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/Felakasztot_ember_KICSIKE.png"))); // NOI18N
        getContentPane().add(fember);
        fember.setBounds(300, 200, 190, 430);

        aember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/emberke.png"))); // NOI18N
        getContentPane().add(aember);
        aember.setBounds(280, 360, 170, 325);

        alja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/akasztofa_alj.png"))); // NOI18N
        alja.setText("jLabel1");
        getContentPane().add(alja);
        alja.setBounds(60, 640, 470, 80);

        kozepe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/akasztofa_közép.png"))); // NOI18N
        getContentPane().add(kozepe);
        kozepe.setBounds(20, 230, 250, 440);

        teteje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/akasztofa_teteje.png"))); // NOI18N
        getContentPane().add(teteje);
        teteje.setBounds(0, 190, 600, 110);

        bember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/Nem_felakasztott_ember_KICSIKE (2).png"))); // NOI18N
        getContentPane().add(bember);
        bember.setBounds(480, 340, 230, 390);

        gomba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangmangame/gomba1.png"))); // NOI18N
        getContentPane().add(gomba1);
        gomba1.setBounds(-240, -50, 580, 760);

        kerdes1.setText("Mi az a Backup?");
        getContentPane().add(kerdes1);
        kerdes1.setBounds(750, 200, 300, 14);

        valasz1.setBackground(new java.awt.Color(255, 255, 51));
        valasz1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        valasz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valasz1ActionPerformed(evt);
            }
        });
        getContentPane().add(valasz1);
        valasz1.setBounds(750, 230, 280, 40);

        kerdes2.setText("Kérdés: Melyik számrendszer áll a felsorolt elemekből?  0, 1, 2, 3, 4, 5, 6, 7, 8, 9");
        getContentPane().add(kerdes2);
        kerdes2.setBounds(750, 280, 260, 30);

        valasz2.setBackground(new java.awt.Color(255, 255, 102));
        valasz2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valasz2ActionPerformed(evt);
            }
        });
        getContentPane().add(valasz2);
        valasz2.setBounds(750, 310, 280, 40);

        kerdes3.setText("Kérdés:  Mi a bootolás?");
        getContentPane().add(kerdes3);
        kerdes3.setBounds(750, 370, 280, 14);

        valasz3.setBackground(new java.awt.Color(255, 255, 102));
        valasz3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valasz3ActionPerformed(evt);
            }
        });
        getContentPane().add(valasz3);
        valasz3.setBounds(750, 400, 280, 40);

        kerdes4.setText("Miben rendszerezzük a fájlokat?");
        getContentPane().add(kerdes4);
        kerdes4.setBounds(750, 450, 280, 14);

        valasz4.setBackground(new java.awt.Color(255, 204, 51));
        valasz4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valasz4ActionPerformed(evt);
            }
        });
        getContentPane().add(valasz4);
        valasz4.setBounds(750, 480, 280, 40);

        jLab_W.setText("jLabel1");
        getContentPane().add(jLab_W);
        jLab_W.setBounds(620, 60, 110, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int w=0;
    private void valasz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valasz1ActionPerformed
        // Kérdés:  Mi az a Backup?
        String V1=valasz1.getText();
        //int w =Integer.parseInt(jLab_W.getText());
        ArrayList<String> Jvalasz1 = new ArrayList<String>();
            Jvalasz1.add("Biztonsági másolat");
            Jvalasz1.add("biztonsági másolat");
            Jvalasz1.add("Biztonságimásolat");
            Jvalasz1.add("Biztonsagi masolat");
            Jvalasz1.add("biztonsagi masolat");
            Jvalasz1.add("Biztonsagimasolat");
            Jvalasz1.add("BIZTONSAGI MASOLAT");
            Jvalasz1.add("BIZTONSÁGI MÁSOLAT");
            Jvalasz1.add("BIZTONSAGIMASOLAT");
            Jvalasz1.add("Biztonsagimasolat");
            Jvalasz1.add("BIZTONSÁGIMÁSOLAT");
            System.out.println(Jvalasz1);
   
        if( Jvalasz1.contains(V1)){

            jLab_W.setText(""+w);
            kerdes2.setVisible(true);
            valasz2.setVisible(true);
            valasz1.setEnabled(false);
        }
        else{
            w=w+1;
            jLab_W.setText(""+w);
            kerdes2.setVisible(true);
            valasz2.setVisible(true);
            valasz1.setEnabled(false);
            
            alja.setVisible(true);
        
        }
    }//GEN-LAST:event_valasz1ActionPerformed

    private void valasz2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valasz2ActionPerformed
        
        // Kérdés: Melyik számrendszer áll a felsorolt elemekből?  0, 1, 2, 3, 4, 5, 6, 7, 8, 9
        String V2=valasz2.getText();
        
        int w1 =Integer.parseInt(jLab_W.getText());
        ArrayList<String> Jvalasz2 = new ArrayList<String>();
            Jvalasz2.add("Decimális");
            Jvalasz2.add("decimális");
            Jvalasz2.add("decimalis");
            Jvalasz2.add("Decimalis");
            Jvalasz2.add("DECIMALIS");
            Jvalasz2.add("DECIMÁLIS");
           
            System.out.println(Jvalasz2);
   
        if( Jvalasz2.contains(V2)){

            jLab_W.setText(""+w1);
            kerdes3.setVisible(true);
            valasz3.setVisible(true);
            valasz2.setEnabled(false);
        }
        else{
            w1=w1+1;
            jLab_W.setText(""+w1);
            kerdes3.setVisible(true);
            valasz3.setVisible(true);
            valasz2.setEnabled(false);
            
            
            if (w1==1)
                alja.setVisible(true);
            else if(w1==2){
               // alja.setVisible(true);
                kozepe.setVisible(true);
                
                alja.setVisible(true); 
           }
        
        }
                                    
    }//GEN-LAST:event_valasz2ActionPerformed
        
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        aember.setVisible(true);
        alja.setVisible(false);
        kozepe.setVisible(false);
        teteje.setVisible(false);
        fember.setVisible(false);
        bember.setVisible(false);
        
        kerdes2.setVisible(false);
        valasz2.setVisible(false);
        kerdes3.setVisible(false);
        valasz3.setVisible(false);
        kerdes4.setVisible(false);
        valasz4.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void valasz3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valasz3ActionPerformed
        // TODO add your handling code here:
        // Kérdés:  Mi a bootolás?
        String V3=valasz3.getText();
        
        int w1 =Integer.parseInt(jLab_W.getText());
        ArrayList<String> Jvalasz3 = new ArrayList<String>();
            Jvalasz3.add("Rendszerbetöltés"); //Írd át rosszul írtad
            Jvalasz3.add("rendszerbetöltés");
            Jvalasz3.add("Rendszerbetoltes");
            Jvalasz3.add("rendszerbetoltes");
            Jvalasz3.add("RENDSZERBETÖLTÉS");
            Jvalasz3.add("RENDSZERBETOLTES");
           
            System.out.println(Jvalasz3);
   
        if( Jvalasz3.contains(V3)){

            jLab_W.setText(""+w1);
            kerdes4.setVisible(true);
            valasz4.setVisible(true);
            valasz3.setEnabled(false);
        }
        else{
            w1=w1+1;
            jLab_W.setText(""+w1);
            
                if (w1 ==1){
                    alja.setVisible(true);
                    valasz4.setVisible(true);
                    valasz3.setEnabled(false);
                    kerdes4.setVisible(true);
                }
                else if (w1==2){
                     kozepe.setVisible(true);
                     valasz4.setVisible(true);
                     valasz3.setEnabled(false);
                     kerdes4.setVisible(true);
                }
                else if (w1==3){
                    teteje.setVisible(true);
                    valasz4.setVisible(true);
                    kerdes4.setVisible(true);
                    valasz3.setEnabled(false);
                   
                }
        
        }
    }//GEN-LAST:event_valasz3ActionPerformed

    private void valasz4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valasz4ActionPerformed
       
        // Kérdés:  Miben rendszerezzük a fájlokat?

        String V4=valasz4.getText();
        ArrayList<String> Jvalasz4 = new ArrayList<String>();
            Jvalasz4.add("Mappákban");
            Jvalasz4.add("mappákban");
            Jvalasz4.add("Mappakban");
            Jvalasz4.add("mappakban");
            Jvalasz4.add("MAPPÁKBAN");
            Jvalasz4.add("MAPPAKBAN");
            
           
            System.out.println(Jvalasz4);
   
        
        
        int w1=Integer.parseInt(jLab_W.getText());
        valasz3.setEnabled(false);
        valasz4.setEnabled(false);
        alja.setVisible(true);
        kozepe.setVisible(true);
        teteje.setVisible(true);
        //Ha ezek már látaszódnak ha 3 rossz válasz volt akkor ezek jhelenítődnek meg
        if( Jvalasz4.contains(V4)){

           jLab_W.setText(""+w1);
           aember.setVisible(false);
           //bember.setVisible(true);
           TheGame g=new TheGame();
                g.setVisible(false);
                g.dispose();
           
        if(w1 < 1){
         bember.setVisible(true);
         
        }
           
       
        //rosz válasznál ezek megjelnítődnek
        }  else {
           w1=w1+1;
           jLab_W.setText(""+w1);
           alja.setVisible(true);
           kozepe.setVisible(true);
           teteje.setVisible(true);
           fember.setVisible(true);
           aember.setVisible(false);
           TheGame g=new TheGame();
                g.setVisible(false);
                g.dispose();
        }
        if(w1 == 0){

                System.out.println("Szuper vagy 10% kedvezmény. NYERTÉL");
                ToWin tw=new ToWin();
                tw.setVisible(true);
                java.sql.Connection con = null;
                PreparedStatement pst = null;
                PreparedStatement stmt = null;
                ResultSet rs = null;
        
        try{
            
            con = DriverManager.getConnection("jdbc:mysql://localhost/webshopdatabase","root", ""); 
            
             stmt = con.prepareStatement (" UPDATE user SET game_points=? WHERE mail=? ");
             
                    
                    int game_points;
                    
                    game_points= 1;
                    
                        stmt.setInt(1 , game_points );
                        stmt.setString(2, Mail.mail);
                        System.out.println("e-mail cím valid");

                        stmt.executeUpdate();
                        System.out.println(game_points);
                        System.out.println("A pontszám feltöltve  a megfelelő email című felhasználóhoz");
        con.close();    

        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }
      
     
       
        }else{
            System.out.println("Vesztettél");
                TheGame g=new TheGame();
                g.setVisible(false);
                g.dispose();
                ToLose tl=new ToLose();
                tl.setVisible(true);
                
                System.out.println(w1);
               
                 //JFrame TheGame = new JFrame("Exit on Close Example");
                
                //g.setDefaultCloseOperation(TheGame.EXIT_ON_CLOSE);
                //TheGame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
       
        
    }//GEN-LAST:event_valasz4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aember;
    private javax.swing.JLabel alja;
    private javax.swing.JLabel bember;
    private javax.swing.JLabel fember;
    private javax.swing.JLabel gomba1;
    private javax.swing.JLabel hatter;
    private javax.swing.JLabel jLab_W;
    private javax.swing.JLabel kerdes1;
    private javax.swing.JLabel kerdes2;
    private javax.swing.JLabel kerdes3;
    private javax.swing.JLabel kerdes4;
    private javax.swing.JLabel kozepe;
    private javax.swing.JLabel teteje;
    private javax.swing.JTextField valasz1;
    private javax.swing.JTextField valasz2;
    private javax.swing.JTextField valasz3;
    private javax.swing.JTextField valasz4;
    // End of variables declaration//GEN-END:variables

   
}
